# when daemon is False, main.py执行完后就退出了， 留下thread自己运行，带来的问题是main.py中定义的变量也一起退出了。
# TODO 这个需要测试一下
